import type { CityConfig } from "@/types";

export const DFW_CITIES: CityConfig[] = [
  {
    slug: "dallas",
    name: "Dallas",
    county: "Dallas County",
    metaTitle: "Dallas Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Dallas? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Dallas",
    heroSubheadline: "Fast response across Dallas — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Dallas?", answer: "Emergency plumbing rates in Dallas typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Dallas?", answer: "Our Dallas plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Dallas?", answer: "We handle all plumbing emergencies in Dallas including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Dallas?", answer: "Yes, we serve all Dallas neighborhoods including Uptown, Deep Ellum, Oak Lawn, Highland Park, Lake Highlands, and surrounding areas." },
      { question: "Are you available 24/7 in Dallas?", answer: "Absolutely. Our Dallas emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Uptown", "Deep Ellum", "Oak Lawn", "Highland Park", "Lake Highlands"],
  },
  {
    slug: "fort-worth",
    name: "Fort Worth",
    county: "Tarrant County",
    metaTitle: "Fort Worth Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Fort Worth? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Fort Worth",
    heroSubheadline: "Fast response across Fort Worth — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Fort Worth?", answer: "Emergency plumbing rates in Fort Worth typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Fort Worth?", answer: "Our Fort Worth plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Fort Worth?", answer: "We handle all plumbing emergencies in Fort Worth including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Fort Worth?", answer: "Yes, we serve all Fort Worth neighborhoods including Sundance Square, Cultural District, Southside, TCU area, Westover Hills, and surrounding areas." },
      { question: "Are you available 24/7 in Fort Worth?", answer: "Absolutely. Our Fort Worth emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Sundance Square", "Cultural District", "Southside", "TCU Area", "Westover Hills"],
  },
  {
    slug: "arlington",
    name: "Arlington",
    county: "Tarrant County",
    metaTitle: "Arlington Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Arlington? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Arlington",
    heroSubheadline: "Fast response across Arlington — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Arlington?", answer: "Emergency plumbing rates in Arlington typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Arlington?", answer: "Our Arlington plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Arlington?", answer: "We handle all plumbing emergencies in Arlington including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Arlington?", answer: "Yes, we serve all Arlington neighborhoods including Downtown Arlington, Entertainment District, Dalworthington Gardens, Pantego, and surrounding areas." },
      { question: "Are you available 24/7 in Arlington?", answer: "Absolutely. Our Arlington emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Downtown Arlington", "Entertainment District", "Dalworthington Gardens", "Pantego", "South Arlington"],
  },
  {
    slug: "plano",
    name: "Plano",
    county: "Collin County",
    metaTitle: "Plano Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Plano? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Plano",
    heroSubheadline: "Fast response across Plano — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Plano?", answer: "Emergency plumbing rates in Plano typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Plano?", answer: "Our Plano plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Plano?", answer: "We handle all plumbing emergencies in Plano including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Plano?", answer: "Yes, we serve all Plano neighborhoods including Legacy West, Downtown Plano, Willow Bend, Preston Hollow, and surrounding areas." },
      { question: "Are you available 24/7 in Plano?", answer: "Absolutely. Our Plano emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Legacy West", "Downtown Plano", "Willow Bend", "Preston Hollow", "West Plano"],
  },
  {
    slug: "irving",
    name: "Irving",
    county: "Dallas County",
    metaTitle: "Irving Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Irving? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Irving",
    heroSubheadline: "Fast response across Irving — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Irving?", answer: "Emergency plumbing rates in Irving typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Irving?", answer: "Our Irving plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Irving?", answer: "We handle all plumbing emergencies in Irving including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Irving?", answer: "Yes, we serve all Irving neighborhoods including Las Colinas, Valley Ranch, Heritage District, South Irving, and surrounding areas." },
      { question: "Are you available 24/7 in Irving?", answer: "Absolutely. Our Irving emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Las Colinas", "Valley Ranch", "Heritage District", "South Irving", "North Irving"],
  },
  {
    slug: "garland",
    name: "Garland",
    county: "Dallas County",
    metaTitle: "Garland Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Garland? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Garland",
    heroSubheadline: "Fast response across Garland — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Garland?", answer: "Emergency plumbing rates in Garland typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Garland?", answer: "Our Garland plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Garland?", answer: "We handle all plumbing emergencies in Garland including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Garland?", answer: "Yes, we serve all Garland neighborhoods including Downtown Garland, Firewheel, Duck Creek, Rowlett Creek, and surrounding areas." },
      { question: "Are you available 24/7 in Garland?", answer: "Absolutely. Our Garland emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Downtown Garland", "Firewheel", "Duck Creek", "Rowlett Creek", "North Garland"],
  },
  {
    slug: "frisco",
    name: "Frisco",
    county: "Collin County",
    metaTitle: "Frisco Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Frisco? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Frisco",
    heroSubheadline: "Fast response across Frisco — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Frisco?", answer: "Emergency plumbing rates in Frisco typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Frisco?", answer: "Our Frisco plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Frisco?", answer: "We handle all plumbing emergencies in Frisco including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Frisco?", answer: "Yes, we serve all Frisco neighborhoods including Stonebriar, The Star District, Frisco Square, Newman Village, and surrounding areas." },
      { question: "Are you available 24/7 in Frisco?", answer: "Absolutely. Our Frisco emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Stonebriar", "The Star District", "Frisco Square", "Newman Village", "West Frisco"],
  },
  {
    slug: "mckinney",
    name: "McKinney",
    county: "Collin County",
    metaTitle: "McKinney Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in McKinney? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in McKinney",
    heroSubheadline: "Fast response across McKinney — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in McKinney?", answer: "Emergency plumbing rates in McKinney typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in McKinney?", answer: "Our McKinney plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in McKinney?", answer: "We handle all plumbing emergencies in McKinney including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of McKinney?", answer: "Yes, we serve all McKinney neighborhoods including Historic Downtown, Stonebridge Ranch, Craig Ranch, Eldorado, and surrounding areas." },
      { question: "Are you available 24/7 in McKinney?", answer: "Absolutely. Our McKinney emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Historic Downtown", "Stonebridge Ranch", "Craig Ranch", "Eldorado", "Tucker Hill"],
  },
  {
    slug: "grand-prairie",
    name: "Grand Prairie",
    county: "Dallas County",
    metaTitle: "Grand Prairie Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Grand Prairie? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Grand Prairie",
    heroSubheadline: "Fast response across Grand Prairie — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Grand Prairie?", answer: "Emergency plumbing rates in Grand Prairie typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Grand Prairie?", answer: "Our Grand Prairie plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Grand Prairie?", answer: "We handle all plumbing emergencies in Grand Prairie including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Grand Prairie?", answer: "Yes, we serve all Grand Prairie neighborhoods including Epic Central, Lone Star Park area, South Grand Prairie, Dalworth Park, and surrounding areas." },
      { question: "Are you available 24/7 in Grand Prairie?", answer: "Absolutely. Our Grand Prairie emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Epic Central", "Lone Star Park Area", "South Grand Prairie", "Dalworth Park", "North Grand Prairie"],
  },
  {
    slug: "denton",
    name: "Denton",
    county: "Denton County",
    metaTitle: "Denton Emergency Plumber | 24/7 Fast Response | FastFlow Plumbing",
    metaDescription: "Need an emergency plumber in Denton? FastFlow Plumbing offers 24/7 service with 30-minute response times. Call now for burst pipes, drain cleaning, leak detection & more.",
    heroHeadline: "24/7 Emergency Plumber in Denton",
    heroSubheadline: "Fast response across Denton — our trucks arrive within 30 minutes",
    faqs: [
      { question: "How much does an emergency plumber cost in Denton?", answer: "Emergency plumbing rates in Denton typically range from $150-$500 depending on the issue. We provide upfront pricing with no hidden fees before any work begins." },
      { question: "How fast can a plumber get to my house in Denton?", answer: "Our Denton plumbing trucks are dispatched 24/7 and typically arrive within 30 minutes of your call." },
      { question: "What plumbing emergencies do you handle in Denton?", answer: "We handle all plumbing emergencies in Denton including burst pipes, drain clogs, water heater failures, gas leaks, sewer backups, toilet overflows, and leak detection." },
      { question: "Do you serve all areas of Denton?", answer: "Yes, we serve all Denton neighborhoods including Downtown Denton, UNT area, TWU area, Robson Ranch, and surrounding areas." },
      { question: "Are you available 24/7 in Denton?", answer: "Absolutely. Our Denton emergency plumbing team is available 24 hours a day, 7 days a week, including holidays. Call anytime and we will be there." },
    ],
    nearbyAreas: ["Downtown Denton", "UNT Area", "TWU Area", "Robson Ranch", "Corinth"],
  },
];